stlog: Adapt and cover
system-transparency/stboot pull request #56
Opened 2022-03-25 14:12 UTC by ChriMarMe

stlog/StandardLogger:
* Allow to pass writer into standard logger for testability
* Rewrite tests to increase coverage of standard logger

Signed-off-by: Christopher Meis <christopher.meis@9elements.com>

2022-03-25 16:20 UTC, jensdrenhaus requested changes

2022-03-25 16:20 UTC, jensdrenhaus commented on stlog/log_test.go
> +		})
Well done! 
Maybe put this in `std_test.go`.

2022-03-25 16:20 UTC, jensdrenhaus commented on stlog/log_test.go
> +	}
Where is the test condition?
A meaningful thing would be to test if calls to `Error()`, `Warn()`, `Info()`, `Debug()` only produce output when the log level is set accordingly.

2022-03-25 16:20 UTC, jensdrenhaus commented on stlog/log_test.go
> +	}
What is tested here?

2022-03-28 09:22 UTC, ChriMarMe commented on stlog/log_test.go
> +	}
Only coverage

2022-03-29 14:15 UTC, jensdrenhaus commented
@ChriMarMe take a look.
Do you have an idea of some smarter/shorter/more elegant way of testing log levels in `TestStandardLoggerLevel()` in std_test.go`?

2022-03-30 06:26 UTC, ChriMarMe commented
@jensdrenhaus LGTM. Can't think of a different, more elegant way tbh.

2022-03-30 07:55 UTC, jensdrenhaus approved these changes

2022-03-30 07:57 UTC, merged