Rework stboot flags to utilize stlog properly
system-transparency/stboot pull request #57
Opened 2022-03-28 10:49 UTC by ChriMarMe

Signed-off-by: Christopher Meis <christopher.meis@9elements.com>

2022-03-28 15:26 UTC, jensdrenhaus reviewed
Great!
I gues we should bring in #56 first?

2022-03-28 15:26 UTC, jensdrenhaus commented on stlog/log.go
> +	getLogLevel() LogLevel
go getter usually has no get, `logLevel()`

2022-03-29 06:33 UTC, ChriMarMe commented
Yes, #56 comes first.

2022-03-30 09:53 UTC, jensdrenhaus reviewed
The new log level getters should be easy to cover in the `log_test.go` and std_test.go`

2022-03-30 10:21 UTC, jensdrenhaus requested changes

2022-03-30 10:21 UTC, jensdrenhaus commented on stlog/syslog_test.go
> +		t.Run(tt.name+" Kernel Logger", func(t *testing.T) {
Remove equivalent t.Run in line 67ff ?

2022-03-30 10:35 UTC, ChriMarMe commented on stlog/syslog_test.go
> +		t.Run(tt.name+" Kernel Logger", func(t *testing.T) {
whoopsie

2022-03-30 11:06 UTC, jensdrenhaus reviewed
Alright! Squash commits and we are done here.

2022-04-01 08:42 UTC, jensdrenhaus approved these changes

2022-04-01 08:42 UTC, merged